### ISSUE TITLE
GUI Mockups für Android-App erstellen

### ISSUE THREAD

**Issue by kahmannf** [kahmannf/EIT62-TMS#1]
Es werden GUI-Mockups für die TMS-Android App benötigt.
Folgende Ansichten sollten mindestens gemockt werden:
- Ticketliste mit Filter
- Projekt erstellen
- Ticket erstellen
- Projekt verwalten (mitarbeiter hinzufügen, etc)
- Ticket bearbeiten (bearbeiter oder status verändern, kommentar hinzufügen)

**Comment by artursinderovski** [comment]
Done
